CREATE TABLE tmc_metadata (
    tmc text PRIMARY KEY,
    road text,
    direction text,
    intersection text,
    state text,
    county text,
    zip text,
    start_latitude double precision,
    start_longitude double precision,
    end_latitude double precision,
    end_longitude double precision,
    miles double precision,
    road_order double precision,
    timezone_name text,
    road_type text,
    country text,
    tmclinear text,
    frc integer,
    f_system integer,
    urban_code integer,
    thrulanes integer,
    aadt integer,
    active_start_date timestamptz,
    active_end_date timestamptz
);