-- ============================================================================
-- CBI MULTI-CORRIDOR BOOTSTRAP / MIGRATION
-- PostgreSQL 17.x | Schema: "Year_2025"
--
-- SAFE TO RE-RUN.
--
-- Prerequisites:
--   "Year_2025".tmc_metadata
--   "Year_2025".probe_readings
--   "Year_2025".congestion_events
--
-- Corridor discovery:
--   Automatically registers every standard Interstate route/direction found
--   in tmc_metadata with at least 3 TMCs. This includes routes such as:
--   I-20, I-75, I-85, I-285, I-575, I-675, I-985, and I-75/I-85 when present.
--
-- Intentionally excluded by the default regex:
--   HOV-only and TOLL-only road labels such as I-75-TOLL or I-75 HOV LANE.
--   These are operationally distinct facilities and should be added explicitly
--   if you want them analyzed as separate corridors.
-- ============================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS "Year_2025";

-- ---------------------------------------------------------------------------
-- 1. Corridor registry
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Year_2025".corridor_definitions (
    corridor_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    road text NOT NULL,
    direction text NOT NULL,
    corridor_name text NOT NULL,
    corridor_group text NOT NULL DEFAULT 'Interstate',
    is_active boolean NOT NULL DEFAULT true,
    congestion_ratio double precision NOT NULL DEFAULT 0.70,
    UNIQUE (road, direction)
);

-- Automatically discover all standard Interstate road/direction pairs.
WITH candidates AS (
    SELECT
        road,
        direction,
        COUNT(*) AS segment_count
    FROM "Year_2025".tmc_metadata
    WHERE road ~ '^I-[0-9]+(/I-[0-9]+)?$'
      AND direction IS NOT NULL
      AND BTRIM(direction) <> ''
    GROUP BY road, direction
    HAVING COUNT(*) >= 3
)
INSERT INTO "Year_2025".corridor_definitions (
    road,
    direction,
    corridor_name,
    corridor_group,
    is_active
)
SELECT
    road,
    direction,
    CASE
        WHEN road = 'I-75/I-85' THEN
            'Downtown Connector ' ||
            INITCAP(LOWER(direction))
        ELSE
            road || ' ' || INITCAP(LOWER(direction))
    END,
    'Interstate',
    true
FROM candidates
ON CONFLICT (road, direction) DO UPDATE SET
    corridor_name = EXCLUDED.corridor_name,
    corridor_group = EXCLUDED.corridor_group,
    is_active = true;

CREATE INDEX IF NOT EXISTS idx_corridor_definitions_active
ON "Year_2025".corridor_definitions (is_active, road, direction);

-- ---------------------------------------------------------------------------
-- 2. Ordered corridor segment registry
-- Rebuilt each run so newly added corridors/metadata are picked up.
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS "Year_2025".corridor_segments;

CREATE TABLE "Year_2025".corridor_segments AS
SELECT
    d.corridor_id,
    d.corridor_name,
    ROW_NUMBER() OVER (
        PARTITION BY d.corridor_id
        ORDER BY m.road_order, m.tmc
    )::integer AS segment_order,
    m.tmc,
    m.road,
    m.direction,
    m.intersection,
    m.miles::double precision AS miles,
    m.road_order,
    m.start_latitude,
    m.start_longitude,
    m.end_latitude,
    m.end_longitude
FROM "Year_2025".corridor_definitions AS d
JOIN "Year_2025".tmc_metadata AS m
  ON m.road = d.road
 AND m.direction = d.direction
WHERE d.is_active;

ALTER TABLE "Year_2025".corridor_segments
ADD CONSTRAINT corridor_segments_pk
PRIMARY KEY (corridor_id, segment_order);

CREATE UNIQUE INDEX idx_corridor_segments_corridor_tmc
ON "Year_2025".corridor_segments (corridor_id, tmc);

CREATE INDEX idx_corridor_segments_tmc
ON "Year_2025".corridor_segments (tmc);

CREATE INDEX idx_corridor_segments_road_direction
ON "Year_2025".corridor_segments (road, direction);

ANALYZE "Year_2025".corridor_segments;

-- ---------------------------------------------------------------------------
-- 3. Ensure recurring bottleneck tables are multi-corridor safe
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Year_2025".segment_recurring_bottlenecks (
    bottleneck_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corridor text NOT NULL,
    direction text NOT NULL,
    peak_segment_order integer NOT NULL,
    start_segment_order integer NOT NULL,
    end_segment_order integer NOT NULL,
    start_mile double precision,
    end_mile double precision,
    segment_count integer,
    representative_intersection text,
    peak_occurrence_pct double precision,
    maximum_raw_occurrence_pct double precision,
    annual_mile_hours double precision,
    average_congested_minutes double precision,
    p95_congested_minutes double precision,
    average_congested_speed_ratio double precision
);

-- Existing single-corridor installations may have a plain integer PK.
-- Convert it to identity once; if it is already identity, do nothing.
DO $$
DECLARE
    identity_status text;
    max_existing_id bigint;
    seq_name text;
BEGIN
    SELECT is_identity
    INTO identity_status
    FROM information_schema.columns
    WHERE table_schema = 'Year_2025'
      AND table_name = 'segment_recurring_bottlenecks'
      AND column_name = 'bottleneck_id';

    IF identity_status = 'NO' THEN
        SELECT COALESCE(MAX(bottleneck_id), 0)
        INTO max_existing_id
        FROM "Year_2025".segment_recurring_bottlenecks;

        EXECUTE format(
            'ALTER TABLE "Year_2025".segment_recurring_bottlenecks
             ALTER COLUMN bottleneck_id
             ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
            max_existing_id + 1
        );
    END IF;

    SELECT pg_get_serial_sequence(
        '"Year_2025".segment_recurring_bottlenecks',
        'bottleneck_id'
    )
    INTO seq_name;

    IF seq_name IS NOT NULL THEN
        SELECT COALESCE(MAX(bottleneck_id), 0)
        INTO max_existing_id
        FROM "Year_2025".segment_recurring_bottlenecks;

        IF max_existing_id > 0 THEN
            PERFORM setval(seq_name, max_existing_id, true);
        END IF;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_recurring_bottlenecks_corridor
ON "Year_2025".segment_recurring_bottlenecks
(corridor, direction);

CREATE TABLE IF NOT EXISTS "Year_2025".segment_bottleneck_membership (
    bottleneck_id integer NOT NULL
        REFERENCES "Year_2025".segment_recurring_bottlenecks(bottleneck_id)
        ON DELETE CASCADE,
    segment_order integer NOT NULL,
    PRIMARY KEY (bottleneck_id, segment_order)
);

-- ---------------------------------------------------------------------------
-- 4. Shared segment-level tables
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Year_2025".segment_daily (
    corridor_id integer NOT NULL
        REFERENCES "Year_2025".corridor_definitions(corridor_id),
    analysis_date date NOT NULL,
    segment_order integer NOT NULL,
    tmc text NOT NULL,
    intersection text,
    miles double precision,
    observed_intervals integer,
    congested_intervals integer,
    congested_minutes integer,
    average_speed_ratio double precision,
    congested_average_speed_ratio double precision,
    PRIMARY KEY (corridor_id, analysis_date, segment_order)
);

CREATE INDEX IF NOT EXISTS idx_segment_daily_corridor_date
ON "Year_2025".segment_daily (corridor_id, analysis_date);

CREATE TABLE IF NOT EXISTS "Year_2025".segment_profile (
    corridor_id integer NOT NULL
        REFERENCES "Year_2025".corridor_definitions(corridor_id),
    segment_order integer NOT NULL,
    tmc text,
    intersection text,
    miles double precision,
    analyzed_days integer,
    occurrence_days integer,
    weekday_occurrence_pct double precision,
    avg_congested_minutes_occurrence_day double precision,
    median_congested_minutes double precision,
    p95_congested_minutes double precision,
    annual_segment_mile_hours double precision,
    average_congested_speed_ratio double precision,
    PRIMARY KEY (corridor_id, segment_order)
);

-- ---------------------------------------------------------------------------
-- 5. Event-day completion ledger
-- Important: congestion_events alone cannot prove a zero-event day completed.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Year_2025".corridor_event_days (
    corridor_id integer NOT NULL
        REFERENCES "Year_2025".corridor_definitions(corridor_id),
    analysis_date date NOT NULL,
    status text NOT NULL CHECK (status IN ('success', 'failed')),
    event_count integer,
    processed_at timestamptz NOT NULL DEFAULT now(),
    error_message text,
    PRIMARY KEY (corridor_id, analysis_date)
);

-- Backfill successful event days that already exist in congestion_events.
INSERT INTO "Year_2025".corridor_event_days (
    corridor_id,
    analysis_date,
    status,
    event_count
)
SELECT
    d.corridor_id,
    e.analysis_date,
    'success',
    COUNT(*)::integer
FROM "Year_2025".congestion_events AS e
JOIN "Year_2025".corridor_definitions AS d
  ON d.road = e.corridor
 AND d.direction = e.direction
GROUP BY d.corridor_id, e.analysis_date
ON CONFLICT (corridor_id, analysis_date) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 6. Daily bottleneck characterization
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Year_2025".bottleneck_daily_metrics (
    bottleneck_id integer NOT NULL
        REFERENCES "Year_2025".segment_recurring_bottlenecks(bottleneck_id)
        ON DELETE CASCADE,
    analysis_date date NOT NULL,
    occurrence boolean NOT NULL,
    onset_time timestamp,
    peak_time timestamp,
    clearance_time timestamp,
    active_congestion_minutes integer,
    episode_duration_minutes integer,
    maximum_queue_miles double precision,
    average_queue_miles double precision,
    queue_mile_hours double precision,
    maximum_congested_segments integer,
    average_congested_speed_ratio double precision,
    minimum_speed_ratio double precision,
    queue_growth_rate_mph double precision,
    queue_dissipation_rate_mph double precision,
    PRIMARY KEY (bottleneck_id, analysis_date)
);

CREATE INDEX IF NOT EXISTS idx_bottleneck_daily_date
ON "Year_2025".bottleneck_daily_metrics
(analysis_date, bottleneck_id);

-- ---------------------------------------------------------------------------
-- 7. Pipeline log
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Year_2025".corridor_pipeline_runs (
    run_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    corridor_id integer NOT NULL
        REFERENCES "Year_2025".corridor_definitions(corridor_id),
    stage text NOT NULL,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    status text NOT NULL DEFAULT 'running',
    detail text
);

CREATE INDEX IF NOT EXISTS idx_corridor_pipeline_runs_corridor
ON "Year_2025".corridor_pipeline_runs
(corridor_id, run_id DESC);

-- ---------------------------------------------------------------------------
-- 8. Multi-corridor dashboard views
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW "Year_2025".vw_bottleneck_annual_dashboard AS
SELECT
    b.bottleneck_id,
    b.corridor,
    b.direction,
    b.peak_segment_order,
    b.start_segment_order,
    b.end_segment_order,
    b.start_mile,
    b.end_mile,
    b.representative_intersection,
    COUNT(*) AS analyzed_days,
    COUNT(*) FILTER (WHERE dm.occurrence) AS occurrence_days,
    ROUND(
        (100.0 * COUNT(*) FILTER (WHERE dm.occurrence) / NULLIF(COUNT(*), 0))::numeric,
        1
    ) AS occurrence_pct,
    ROUND(
        AVG(dm.active_congestion_minutes) FILTER (WHERE dm.occurrence)::numeric,
        1
    ) AS avg_active_minutes,
    ROUND(
        PERCENTILE_CONT(0.50) WITHIN GROUP (
            ORDER BY dm.active_congestion_minutes
        ) FILTER (WHERE dm.occurrence)::numeric,
        1
    ) AS median_active_minutes,
    ROUND(
        PERCENTILE_CONT(0.95) WITHIN GROUP (
            ORDER BY dm.active_congestion_minutes
        ) FILTER (WHERE dm.occurrence)::numeric,
        1
    ) AS p95_active_minutes,
    ROUND(
        AVG(dm.maximum_queue_miles) FILTER (WHERE dm.occurrence)::numeric,
        2
    ) AS avg_max_queue_miles,
    ROUND(
        PERCENTILE_CONT(0.95) WITHIN GROUP (
            ORDER BY dm.maximum_queue_miles
        ) FILTER (WHERE dm.occurrence)::numeric,
        2
    ) AS p95_max_queue_miles,
    ROUND(MAX(dm.maximum_queue_miles)::numeric, 2) AS annual_max_queue_miles,
    ROUND(SUM(dm.queue_mile_hours)::numeric, 2) AS annual_queue_mile_hours,
    ROUND(
        AVG(dm.average_congested_speed_ratio) FILTER (WHERE dm.occurrence)::numeric,
        3
    ) AS avg_congested_speed_ratio,
    ROUND(
        AVG(dm.queue_growth_rate_mph) FILTER (WHERE dm.occurrence)::numeric,
        2
    ) AS avg_queue_growth_rate_mph,
    ROUND(
        AVG(dm.queue_dissipation_rate_mph) FILTER (WHERE dm.occurrence)::numeric,
        2
    ) AS avg_queue_dissipation_rate_mph
FROM "Year_2025".segment_recurring_bottlenecks AS b
JOIN "Year_2025".bottleneck_daily_metrics AS dm
  ON dm.bottleneck_id = b.bottleneck_id
GROUP BY
    b.bottleneck_id,
    b.corridor,
    b.direction,
    b.peak_segment_order,
    b.start_segment_order,
    b.end_segment_order,
    b.start_mile,
    b.end_mile,
    b.representative_intersection;

DROP VIEW IF EXISTS "Year_2025".vw_bottleneck_dashboard_ranked;

CREATE VIEW "Year_2025".vw_bottleneck_dashboard_ranked AS
SELECT
    a.*,
    ROUND(
        (
            a.annual_queue_mile_hours
            * a.occurrence_pct / 100.0
            * (1.0 - a.avg_congested_speed_ratio)
        )::numeric,
        2
    ) AS severity_index,
    RANK() OVER (
        PARTITION BY a.corridor, a.direction
        ORDER BY
            a.annual_queue_mile_hours
            * a.occurrence_pct / 100.0
            * (1.0 - a.avg_congested_speed_ratio) DESC
    ) AS corridor_severity_rank,
    RANK() OVER (
        ORDER BY
            a.annual_queue_mile_hours
            * a.occurrence_pct / 100.0
            * (1.0 - a.avg_congested_speed_ratio) DESC
    ) AS network_severity_rank
FROM "Year_2025".vw_bottleneck_annual_dashboard AS a;

CREATE OR REPLACE VIEW "Year_2025".vw_bottleneck_monthly_dashboard AS
SELECT
    dm.bottleneck_id,
    b.corridor,
    b.direction,
    b.representative_intersection,
    DATE_TRUNC('month', dm.analysis_date)::date AS month,
    COUNT(*) AS analyzed_days,
    COUNT(*) FILTER (WHERE dm.occurrence) AS occurrence_days,
    ROUND(
        (100.0 * COUNT(*) FILTER (WHERE dm.occurrence) / NULLIF(COUNT(*), 0))::numeric,
        1
    ) AS occurrence_pct,
    ROUND(
        AVG(dm.active_congestion_minutes) FILTER (WHERE dm.occurrence)::numeric,
        1
    ) AS avg_active_minutes,
    ROUND(
        AVG(dm.maximum_queue_miles) FILTER (WHERE dm.occurrence)::numeric,
        2
    ) AS avg_max_queue_miles,
    ROUND(MAX(dm.maximum_queue_miles)::numeric, 2) AS max_queue_miles,
    ROUND(SUM(dm.queue_mile_hours)::numeric, 2) AS queue_mile_hours,
    ROUND(
        AVG(dm.average_congested_speed_ratio) FILTER (WHERE dm.occurrence)::numeric,
        3
    ) AS avg_congested_speed_ratio
FROM "Year_2025".bottleneck_daily_metrics AS dm
JOIN "Year_2025".segment_recurring_bottlenecks AS b
  ON b.bottleneck_id = dm.bottleneck_id
GROUP BY
    dm.bottleneck_id,
    b.corridor,
    b.direction,
    b.representative_intersection,
    DATE_TRUNC('month', dm.analysis_date);

CREATE OR REPLACE VIEW "Year_2025".vw_bottleneck_weekday_dashboard AS
SELECT
    dm.bottleneck_id,
    b.corridor,
    b.direction,
    b.representative_intersection,
    EXTRACT(ISODOW FROM dm.analysis_date)::integer AS weekday_number,
    TO_CHAR(dm.analysis_date, 'Dy') AS weekday_name,
    COUNT(*) AS analyzed_days,
    COUNT(*) FILTER (WHERE dm.occurrence) AS occurrence_days,
    ROUND(
        (100.0 * COUNT(*) FILTER (WHERE dm.occurrence) / NULLIF(COUNT(*), 0))::numeric,
        1
    ) AS occurrence_pct,
    ROUND(
        AVG(dm.active_congestion_minutes) FILTER (WHERE dm.occurrence)::numeric,
        1
    ) AS avg_active_minutes,
    ROUND(
        AVG(dm.maximum_queue_miles) FILTER (WHERE dm.occurrence)::numeric,
        2
    ) AS avg_max_queue_miles,
    ROUND(SUM(dm.queue_mile_hours)::numeric, 2) AS queue_mile_hours
FROM "Year_2025".bottleneck_daily_metrics AS dm
JOIN "Year_2025".segment_recurring_bottlenecks AS b
  ON b.bottleneck_id = dm.bottleneck_id
GROUP BY
    dm.bottleneck_id,
    b.corridor,
    b.direction,
    b.representative_intersection,
    EXTRACT(ISODOW FROM dm.analysis_date),
    TO_CHAR(dm.analysis_date, 'Dy');

COMMIT;

-- ---------------------------------------------------------------------------
-- Validation / inventory
-- ---------------------------------------------------------------------------
SELECT
    d.corridor_id,
    d.corridor_name,
    d.road,
    d.direction,
    COUNT(s.tmc) AS segments,
    ROUND(SUM(s.miles)::numeric, 2) AS miles
FROM "Year_2025".corridor_definitions AS d
LEFT JOIN "Year_2025".corridor_segments AS s
  ON s.corridor_id = d.corridor_id
WHERE d.is_active
GROUP BY d.corridor_id, d.corridor_name, d.road, d.direction
ORDER BY d.road, d.direction;
